export const QUESTIONS = {
    couples: {
        truth: [
            "What's the most romantic thing your partner has ever done for you?",
            "What's one habit your partner has that secretly annoys you?",
            "What's your partner's most embarrassing habit?",
            "Describe your ideal romantic getaway with your partner.",
            "What's one thing you wish your partner would do more often?",
            "What's the biggest argument you and your partner ever had, and how did you resolve it?",
            "What's your favorite physical feature of your partner?",
            "What's one thing you've learned about yourself since being with your partner?",
            "If your partner was an animal, what would they be and why?",
            "What's a secret dream or goal you have for your relationship?",
            "What's one quality your partner has that you wish you had?",
            "What's the most adventurous thing you've done together?",
            "What's your favorite memory with your partner?",
            "What's something you appreciate about your partner that you don't often tell them?",
            "What's a pet peeve you have that your partner does, but you tolerate?",
            "What's the most surprising thing you've learned about your partner?",
            "If you could relive one day with your partner, which day would it be?",
            "What's your partner's most endearing quirk?",
            "What's one thing you want to achieve with your partner in the next year?",
            "What's a song that reminds you of your partner and why?",
            "What’s your partner’s most annoying habit in bed?",
            "What's one thing you've done that your partner doesn't know about?",
            "What's the silliest argument you've ever had with your partner?",
            "What's the best piece of advice your partner has given you?",
            "What's a guilty pleasure you share with your partner?",
            "What's one thing you'd change about your relationship if you could?",
            "What's the most thoughtful gift you've received from your partner?",
            "What's your partner's biggest fear?",
            "What's one thing you're most grateful for about your partner?",
            "What's the most impulsive thing you've done together?"
        ],
        dare: [
            "Give your partner a piggyback ride around the room.",
            "Serenade your partner with a love song.",
            "Let your partner draw a silly face on you with a marker.",
            "Feed your partner a snack blindfolded.",
            "Switch clothes with your partner for the next two rounds.",
            "Give your partner a five-minute foot massage.",
            "Re-enact your first kiss with your partner.",
            "Let your partner pick your outfit for tomorrow.",
            "Whisper something dirty in your partner's ear.",
            "Do your partner's hair (or apply make-up) in a silly way.",
            "Share an embarrassing story about your partner.",
            "Kiss your partner for 30 seconds straight.",
            "Write a short, spontaneous love poem for your partner and read it aloud.",
            "Give your partner a sensual shoulder massage.",
            "Perform a cheesy pickup line on your partner.",
            "Recreate your favorite couple's photo.",
            "Let your partner choose one of your social media posts to delete.",
            "Give your partner a sincere compliment every time they take a sip for the rest of the game.",
            "Dance slowly with your partner to an imaginary song.",
            "Let your partner tickle you for 20 seconds.",
            "Swap a piece of clothing with your partner for the rest of the round.",
            "Blindfold your partner and give them three mystery foods to taste.",
            "Give your partner a 'spa treatment' with whatever is available (e.g., hand massage, face mask).",
            "Propose to your partner in a dramatic way.",
            "Write 'I love you' on your partner's forehead with lipstick (or washable marker).",
            "Let your partner wax one small patch of your arm or leg (if you have wax available).",
            "Give your partner a lap dance.",
            "Do 10 push-ups with your partner on your back (if safe).",
            "Feed your partner a drink without using your hands.",
            "Have a staring contest with your partner; the first to blink drinks."
        ]
    },
    spicy: {
        truth: [
            "What’s the most adventurous thing you’ve done in bed?",
            "What’s your biggest turn-on?",
            "What’s your biggest turn-off?",
            "What’s one thing you've pretended to enjoy sexually?",
            "What’s your wildest fantasy?",
            "What’s the most embarrassing thing that’s happened to you during sex?",
            "Have you ever cheated on a partner? If so, why?",
            "What’s one question you're afraid to ask your partner about sex?",
            "What’s the most unusual place you’ve had sex?",
            "What’s one thing you’ve always wanted to try in bed but haven't?",
            "What's your favorite thing about your own body?",
            "What’s a secret about your sex life no one knows?",
            "Describe your ideal romantic date that ends with intimacy.",
            "What's your preferred position?",
            "What's your favorite part of someone else's body?",
            "Have you ever sent nudes?",
            "What’s the craziest thing you’ve done while drunk?",
            "What’s one sex toy you'd recommend?",
            "What's the most daring thing you've worn to feel sexy?",
            "What's one thing that always puts you in the mood?",
            "What’s the earliest age you remember feeling attracted to someone?",
            "What’s a secret crush you’ve had on someone you know?",
            "What’s your biggest insecurity related to intimacy?",
            "What's one sexual experience you regret?",
            "What's the longest you've gone without sex?",
            "What’s your favorite type of foreplay?",
            "What’s one thing you find surprisingly sexy?",
            "Have you ever been caught doing something intimate?",
            "What’s your go-to move to flirt?",
            "What’s the most daring thing you’ve said to someone you were attracted to?"
        ],
        dare: [
            "Take off one item of clothing (or equivalent, e.g., a sock).",
            "Let another player apply a blindfold to you for the next 3 rounds.",
            "Do 10 push-ups or sit-ups.",
            "Give the person to your right a compliment that's only about their body.",
            "Allow another player to choose a body part for you to lick.",
            "Give a sensual massage to the person of your choice for 2 minutes.",
            "Whisper a secret fantasy to the person next to you.",
            "Do a sexy dance for 30 seconds.",
            "Let another player slap your butt.",
            "Take a sip for every person you've kissed in this room.",
            "Kiss the person of your choice passionately for 10 seconds.",
            "Remove your bra (if wearing one) without using your hands.",
            "Let another player pour a drink down your cleavage/chest.",
            "Do a body shot off someone's belly button.",
            "Send a flirty text to someone in your contacts (not in this room).",
            "Lap dance for someone in the room.",
            "Let another player tie your hands behind your back for the next round.",
            "Blindfold someone in the room and feed them a drink.",
            "Remove someone else's sock with your teeth.",
            "Do a shot of hot sauce (if available and safe).",
            "Give a hickey to someone of your choice.",
            "Swap clothes with the person of the opposite gender for the next round.",
            "Write your biggest turn-on on a piece of paper and show everyone.",
            "Let another player give you a 'wedgie' (lightly!).",
            "Lick whipped cream off someone's finger.",
            "Act out your favorite sex position without talking.",
            "Give a very enthusiastic high-five to the sexiest person in the room.",
            "Give a 30-second sensuous back scratch to the person on your left.",
            "Try to make another player blush in 60 seconds.",
            "Let another player give you a temporary tattoo in an 'interesting' place."
        ]
    },
    embarrassing: {
        truth: [
            "What’s the most embarrassing thing you've done in front of a crush?",
            "What’s one thing you do when no one is watching that would embarrass you if others knew?",
            "What’s the most embarrassing thing you’ve ever worn?",
            "What’s your most awkward dating story?",
            "What’s a secret talent you have that's actually quite embarrassing?",
            "What’s the most embarrassing thing your parents have ever done to you?",
            "What’s the most embarrassing thing you've ever said to someone?",
            "What’s a time you completely messed up publicly?",
            "What’s the most embarrassing purchase you’ve ever made?",
            "What’s a weird habit you have?",
            "What’s an embarrassing childhood memory?",
            "What's the most cringe-worthy social media post you've ever made?",
            "What's the most embarrassing nickname you've ever had?",
            "What's something you pretended to know but had no idea about?",
            "What's the most embarrassing thing you've found in your room?",
            "What’s your most embarrassing moment from school?",
            "What’s the most embarrassing thing you’ve ever Googled?",
            "What’s a weird dream you’ve had recently?",
            "What’s the most embarrassing thing that’s happened to you on vacation?",
            "What’s the most awkward thing you’ve ever overheard?",
            "What's your most embarrassing moment involving a toilet?",
            "What's the most embarrassing thing you've done at work/school?",
            "What's one thing you've done that you hope no one ever finds out about?",
            "What's the most embarrassing thing you've done to impress someone?",
            "What's your most embarrassing fashion choice from the past?",
            "What's the most awkward gift you've ever received?",
            "What's the most embarrassing thing you've said to a stranger?",
            "What's your most embarrassing encounter with a celebrity?",
            "What's the most embarrassing thing you've cried over?",
            "What's the most embarrassing pet name you've ever used or been called?"
        ],
        dare: [
            "Do your best impression of a chicken clucking for 30 seconds.",
            "Sing a song entirely in a silly, high-pitched voice.",
            "Let the person to your left draw on your face with a washable marker.",
            "Wear your shirt inside out for the next 3 rounds.",
            "Do 10 jumping jacks while making animal noises.",
            "Tell a joke, but deliver the punchline in a whisper.",
            "Act like a T-Rex for the next minute.",
            "Let another player give you a ridiculous new hairstyle.",
            "Talk in a fake accent for the next 5 minutes.",
            "Do a dramatic reading of a grocery list.",
            "Pretend to be a statue until the next player's turn.",
            "Crawl under the table and retrieve something with your mouth.",
            "Attempt to lick your elbow.",
            "Walk around the room with a pillow tucked under your shirt, pretending to be pregnant.",
            "Do your best impression of a baby crying.",
            "Balance a spoon on your nose for 30 seconds.",
            "Let everyone tickle you for 10 seconds (you can call stop).",
            "Do the Macarena (or another popular silly dance) for a full minute.",
            "Talk like a pirate for the next two questions.",
            "Do your best catwalk strut around the room.",
            "Wear socks on your hands for the next round.",
            "Try to catch a piece of food in your mouth that another player drops from shoulder height.",
            "Do a belly dance for 15 seconds.",
            "Pretend to be a superhero with a ridiculous power and demonstrate it.",
            "Sing 'Happy Birthday' to the wall as if it's your best friend.",
            "Make up a rap about the person to your right.",
            "Perform a magic trick (even if it's a bad one).",
            "Wear a piece of toilet paper stuck to your shoe for the rest of the game.",
            "Do your best impersonation of a famous person struggling with a simple task.",
            "Let another player choose one of your phone contacts for you to send a random emoji to."
        ]
    },
    funny: {
        truth: [
            "What’s the funniest thing you’ve ever witnessed?",
            "What’s the most ridiculous thing you’ve ever cried about?",
            "What’s your most embarrassing public transport moment?",
            "What’s the silliest thing you’ve done to avoid doing something else?",
            "What’s a silly prank you’ve played on someone?",
            "What’s the most absurd rumor you’ve ever heard about yourself?",
            "What’s a weird food combination you actually enjoy?",
            "What’s the most childish thing you still do?",
            "What’s a funny misunderstanding you’ve been involved in?",
            "What’s the weirdest thing you’ve ever said out loud without realizing it?",
            "What’s a funny pet story you have?",
            "What’s the most bizarre thing you’ve ever found?",
            "What’s the strangest dream you’ve ever had?",
            "What’s a funny habit your friend or family member has?",
            "What’s the most awkward thing you’ve done on a first date?",
            "What’s the silliest thing you've ever bought?",
            "What's a funny lie you told as a kid that got you into trouble?",
            "What's the most ridiculous thing you've ever believed?",
            "What's your go-to funny story?",
            "What's the funniest thing that's happened at a party?",
            "What’s the most nonsensical argument you’ve ever had?",
            "What’s a silly thing that instantly makes you laugh?",
            "What’s the funniest thing a child has ever said to you?",
            "What’s a funny mistake you often make?",
            "What’s your funniest travel mishap?",
            "What's the weirdest thing you've eaten on a dare?",
            "What's one thing you find incredibly funny that most people don't?",
            "What's the funniest thing that happened at your job/school?",
            "What's your most embarrassing dancing moment?",
            "What's the funniest thing you've done while drunk or very tired?"
        ],
        dare: [
            "Do your best impression of a stand-up comedian telling a joke.",
            "Try to juggle three random items.",
            "Put on a fashion show with clothes found in the room.",
            "Do an interpretive dance to a commercial jingle.",
            "Pretend to be a news anchor reporting on mundane events in the room.",
            "Do your best chicken dance for 30 seconds.",
            "Talk for a minute without using the letter 'S'.",
            "Perform a dramatic monologue about your favorite snack.",
            "Try to lick your nose.",
            "Do 10 push-ups, but every push-up requires a silly sound.",
            "Wear sunglasses indoors for the rest of the game.",
            "Pretend the floor is lava and navigate across the room without touching it.",
            "Have a silent laugh for 30 seconds.",
            "Try to scare someone in the room.",
            "Do an impression of someone in the room without naming them.",
            "Tell a story using only sounds, no words.",
            "Give a TED Talk on why your favorite obscure item is amazing.",
            "Walk backward for the next 2 minutes.",
            "Try to catch a grape in your mouth from across the room (if safe and available).",
            "Recite the alphabet backward as fast as you can.",
            "Act like a cat for the next round.",
            "Do a funny walk across the room.",
            "Make up a song about the person to your right and sing it.",
            "Do 20 squats while counting loudly in a silly voice.",
            "Try to draw a self-portrait with your eyes closed.",
            "Give a dramatic opera performance of a nursery rhyme.",
            "Speak only in rhymes for the next 5 minutes.",
            "Do your best robot dance for 30 seconds.",
            "Try to drink a glass of water without using your hands.",
            "Make a funny face and hold it for one minute."
        ]
    },
    naughty: {
        truth: [
            "What's your biggest turn-on for a person of the opposite sex?",
            "What's your biggest turn-on for a person of the same sex?",
            "What's the naughtiest thing you've done in public?",
            "What's your favorite part of a man's body?",
            "What's your favorite part of a woman's body?",
            "What’s the raunchiest text you’ve ever sent or received?",
            "What’s one sexual experience you regret not having?",
            "What’s the most inappropriate crush you’ve ever had?",
            "What’s the most extreme thing you’ve done to get someone’s attention?",
            "What’s your most daring sexual fantasy?",
            "What’s the biggest lie you’ve told about your sexual experience?",
            "What’s your favorite piece of lingerie or underwear?",
            "What’s the most scandalous thing you’ve seen someone else do?",
            "What's one thing you would never do in bed, no matter what?",
            "What's your 'type' and why?",
            "What’s the last thing you watched that turned you on?",
            "What’s your preferred method of seduction?",
            "What’s the longest you’ve gone without a shower, and why?",
            "What’s one thing you’ve stolen?",
            "What’s your most embarrassing moment in the bedroom?",
            "What’s the most daring thing you’ve done on a first date?",
            "What’s a secret about your body that no one knows?",
            "What's the naughtiest thought you've had about someone in this room?",
            "What’s one thing you secretly judge others for?",
            "What's your most expensive purchase that you regret?",
            "What’s one thing you would change about your physical appearance?",
            "What’s the most revealing outfit you own?",
            "What’s one thing you do when you’re home alone that you wouldn’t want anyone to see?",
            "What’s the craziest dream you’ve had that involved someone you know?",
            "What’s your biggest fear about aging?"
        ],
        dare: [
            "Take off your socks using only your teeth.",
            "Let the person to your left draw on your leg with a washable marker.",
            "Give the person to your right a lap dance.",
            "Whisper something dirty into the ear of the person across from you.",
            "Do 10 push-ups, but every push-up requires a moan.",
            "Give a passionate kiss to the back of your hand.",
            "Let another player tie your shoelaces together for the next round.",
            "Do a body shot off someone's belly button.",
            "Take a picture of your feet and send it to a friend.",
            "Try to lick your elbow.",
            "Give the person on your left a hickey (lightly!).",
            "Swap an item of clothing with the person of the opposite sex.",
            "Do a sexy walk across the room.",
            "Let another player slap your butt (lightly!).",
            "Whisper your biggest turn-on to the player who asked the question.",
            "Attempt to pop a button on your shirt by flexing (if safe).",
            "Do 5 squats while motorboating the air.",
            "Let another player put ice down your shirt.",
            "Seductively eat a banana (or other available fruit).",
            "Give a sensual foot massage to the person of your choice.",
            "Do a striptease down to your undergarments (or for as long as you dare).",
            "Go outside and yell 'I'm sexy and I know it!'",
            "Kiss the person of your choice on the neck for 10 seconds.",
            "Allow another player to blindfold you and feed you something.",
            "Give the person on your right a wet willy.",
            "Try to touch your nose with your tongue.",
            "Pretend to be a cat in heat.",
            "Wear a bra on your head for the rest of the game (if male, wear it normally).",
            "Give a player a piggyback ride while making animal noises.",
            "Let another player choose one of your social media contacts to send a random, flirty GIF to."
        ]
    }
};